# Generated by Django 3.2.7 on 2021-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Point'),
        ),
    ]
